apiVersion: v1
kind: ConfigMap
metadata:
  name: wpcache
  labels:
    app: wpcache
data:
  config.yaml: |
    server:
      port: :8080
    hosts:
---
apiVersion: v1
kind: Service
metadata:
  name: wpcache
  labels:
    app: wpcache
spec:
  ports:
  - port: 8080
  selector:
    app: wpcache
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wpcache
  labels:
    app: wpcache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wpcache
    spec:
      volumes:
      - name: config
        configMap:
          name: wpcache
          items:
          - key: config.yaml
            path: config.yaml
      containers:
      - name: wpcache
        image: acoshift/wpcache:0.0.1
        args:
        - -config
        - /config/config.yaml
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - name: config
          mountPath: /config
